---
- name: Setup ssh key for root user
  user:
    name: root
    generate_ssh_key: true

- name: Gather required facts
  setup:
    gather_subset:
      - '!all'
      - 'ohai'

- name: Edit yum.conf to not install docs
  lineinfile:
    path: '/etc/yum.conf'
    state: present
    line: 'tstflags=nodocs'
  when: ansible_distribution == "RedHat"

- name: Install pcp
  yum:
    name: ['pcp-zeroconf']
    state: present
  retries: 10
  delay: 5

- name: Start pcp services
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    state: restarted
  with_items:
   - 'pmcd'
   - 'pmlogger'

